#!/usr/bin/env python3
"""Generate opt-in normalization-inert assigned ranges from pinned UnicodeData.
Input: https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
No renderer normalization/shaping/catalogue implementation is used or generated.
"""
import argparse, hashlib
from pathlib import Path

INPUT_SHA256 = '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c'
p = argparse.ArgumentParser()
p.add_argument('--unicode-data', type=Path, required=True)
p.add_argument('--check', action='store_true')
args = p.parse_args()
raw = args.unicode_data.read_bytes()
if hashlib.sha256(raw).hexdigest() != INPUT_SHA256:
    raise SystemExit('expected pinned Unicode 17.0.0 UnicodeData.txt hash')
assigned, excluded = set(), set()
first = None
for line in raw.decode('utf-8').splitlines():
    row = line.split(';')
    cp, name = int(row[0], 16), row[1]
    if name.endswith(', First>'):
        first = cp
    elif name.endswith(', Last>'):
        assert first is not None
        assigned.update(range(first, cp + 1)); first = None
    else:
        assigned.add(cp)
    if int(row[3]):
        excluded.add(cp)
    decomposition = row[5]
    if decomposition and not decomposition.startswith('<'):
        excluded.add(cp)
        parts = [int(part, 16) for part in decomposition.split()]
        # All canonical pairs conservatively include composition-excluded pairs.
        if len(parts) == 2:
            excluded.add(parts[1])
assert first is None
# UAX15/Unicode Standard 3.12 algorithmic decomposition and composition domains.
for lo, hi in [(0x1100,0x1112),(0x1161,0x1175),(0x11a8,0x11c2),(0xac00,0xd7a3),(0xd800,0xdfff)]:
    excluded.update(range(lo, hi + 1))
ranges = []
for cp in sorted(assigned - excluded):
    if ranges and ranges[-1][1] + 1 == cp:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp])
text = '''/** Generated by scripts/generate-font-preload-inert-ranges.py.
 * Unicode 17.0.0 assigned scalars excluding canonical decomposition keys,
 * canonical-pair second operands, nonzero CCC and algorithmic Hangul domains.
 * UnicodeData.txt SHA-256: ''' + INPUT_SHA256 + '''
 * https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
 * UAX15 §12.1 normalization stability applies to assigned strings. Unassigned
 * scalars are intentionally unknown. This proves spelling only, never support.
 * Analysis is invoked only for opt-in demand; flattened worker assets may
 * include these proof bytes even when Google fonts are disabled.
 */
let ranges: readonly number[] | undefined;
/** Flattened consumer workers still include these bytes; first use, not module
 * evaluation, allocates the table. Google-off parsing never invokes it. */
export function fontPreloadInertRanges(): readonly number[] {
  return ranges ??= [
''' + ''.join(f'  0x{lo:x}, 0x{hi:x},\n' for lo, hi in ranges) + '  ];\n}\n'
out = Path(__file__).resolve().parents[1] / 'packages/pptx/src/font-preload-inert-ranges.ts'
if args.check:
    if out.read_text() != text:
        raise SystemExit('font preload inert ranges are stale')
else:
    out.write_text(text)
print(f'{len(ranges)} pinned assigned-inert ranges')
